language: go
go:
  - 1.8
install: go get -v github.com/spf13/hugo
before_script: git clone https://github.com/alanorth/hugo-theme-bootstrap4-blog.git themes/hugo-theme-bootstrap4-blog
script: hugo
sudo: false
dist: trusty
notifications:
  email:
    on_success: never
    on_failure: always

# vim: ts=2 sw=2 et
